const quec_dependencies_json = {
    dependencies: [
        {name: 'react-native-community_blur', version: '3.6.0', platform: 1},
        {name: 'react-native-device-info', version: '10.0.2', platform: 1},
        {name: 'react-native-permissions', version: '3.2.0', platform: 1},
        {name: 'react-native-qr-scanner', version: '1.3.2', platform: 1},
        {name: 'react-native-async-storage', version: '1.17.12', platform: 3},
        {name: 'react-native-image-picker', version: '4.0.3', platform: 3},
        {
            name: 'react-native-color-picker-light',
            version: '1.0.1',
            platform: 3,
        },
        {name: 'react-native', version: '0.64.3', platform: 3},
        {name: 'react-native-reanimated', version: '2.17.0', platform: 3},
        {name: 'react-native-screens', version: '3.17.0', platform: 3},
        {name: 'react-native-safe-area-context', version: '3.4.1', platform: 3},
        {name: 'react-native-gesture-handler', version: '1.10.3', platform: 3},
        {name: 'react-native-localize', version: '2.2.4', platform: 3},
        {name: 'react-native-svg', version: '12.4.4', platform: 3},
        {name: 'react-native-vector-icons', version: '8.1.0', platform: 3},
        {name: 'react-native-i18n', version: '2.0.15', platform: 3},
        {name: 'react-native-fs', version: '2.20.0', platform: 3},
        {name: 'react-native-share', version: '7.9.1', platform: 3},
        {name: 'react-native-view-shot', version: '3.4.0', platform: 3},
        {name: 'react-native-linear-gradient', version: '2.6.2', platform: 3},
        {name: 'react-native-pager-view', version: '5.4.25', platform: 3},
        {name: 'react-native-webview', version: '11.23.1', platform: 3},
        {name: 'react-native-netinfo', version: '9.3.7', platform: 3},
        {name: 'lottie-react-native', version: '5.1.4', platform: 3},
        {name: 'react-native-pdf', version: '6.6.2', platform: 3},
        {name: 'react-native-blob-util', version: '0.16.4', platform: 3},
        {name: 'react-native-video', version: '5.2.1', platform: 3},
        {
            name: 'react-native-orientation-locker',
            version: '1.5.1',
            platform: 3,
        },
        {name: 'react-native-camera-roll', version: '5.6.0', platform: 3},
        {name: 'QuecRNTabModule', version: '1.0.7', platform: 3},
        {name: 'QuecRNDeviceModule', version: '2.11.4', platform: 3},
        {name: 'QuecRNRouterModule', version: '1.4.0', platform: 3},
        {name: 'QuecRNUserModule', version: '1.0.9', platform: 3},
        {name: 'QuecRNMusicModule', version: '1.0.9', platform: 3},
        {name: 'QuecRNColorPickerComponent', version: '1.2.0', platform: 3},
        {name: 'QuecRNLanguageModule', version: '0.1.9', platform: 3},
        {name: 'QuecRNStatusBarModule', version: '1.0.1', platform: 1},
        {name: 'QuecRNLogModule', version: '1.0.6', platform: 3},
        {name: 'QuecRNNetworkModule', version: '1.4.10', platform: 3},
        {name: 'QuecRNGroupModule', version: '1.0.1', platform: 3},
        {name: 'QuecRNBusinessPanelModule', version: '1.1.3', platform: 3},
        {name: 'QuecRNMapComponent', version: '1.8.0', platform: 3},
    ],
    isSupportIPC: [
        {name: 'QuecRNIPCVideoComponent', version: '2.1.11', platform: 3},
        {name: 'QuecRNIPCVideoModule', version: '2.1.9', platform: 3},
    ],
    isMatterSupport: [
        {name: 'QuecRNMatterModule', version: '1.3.1', platform: 3},
    ],
    isAddValuesPushSupport: [
        {name: 'QuecRNAddValuesPushModule', version: '0.0.6', platform: 3},
    ],
}

const quec_name_map_json = {
    '@react-native-community/blur': 'react-native-community_blur',
    '@react-native-community/netinfo': 'react-native-netinfo',
    '@react-native-camera-roll/camera-roll': 'react-native-camera-roll',
    '@react-native-community/cameraroll': 'react-native-camera-roll',
    '@react-native-async-storage/async-storage': 'react-native-async-storage',
    '@quec/rn-device-module': 'QuecRNDeviceModule',
    '@quec/rn-router-module': 'QuecRNRouterModule',
    '@quec/rn-user-module': 'QuecRNUserModule',
    '@quec/rn-music-module': 'QuecRNMusicModule',
    '@quec/rn-language-module': 'QuecRNLanguageModule',
    '@quec/rn-statusbar-module': 'QuecRNStatusBarModule',
    '@quec/rn-log-module': 'QuecRNLogModule',
    '@quec/rn-network-module': 'QuecRNNetworkModule',
    '@quec/rn-matter-module': 'QuecRNMatterModule',
    '@quec/rn-ipcvideo-module': 'QuecRNIPCVideoModule',
    '@quec/rn-ipcvideo-component': 'QuecRNIPCVideoComponent',
    '@quec/rn-map-component': 'QuecRNMapComponent',
    '@quec/rn-colorpicker-component': 'QuecRNColorPickerComponent',
    '@quec/rn-group-module': 'QuecRNGroupModule',
    '@quec/rn-tab-module': 'QuecRNTabModule',
    '@quec/rn-businesspanel-module': 'QuecRNBusinessPanelModule',
    '@quec/rn-add-values-push-module': 'QuecRNAddValuesPushModule',
}

module.exports = {
    quec_dependencies_json,
    quec_name_map_json,
}
